import { START_ZONE_ID, ZONES, zonePlatforms } from './data/zones';
import { createStarterInventory, applyGearStats } from './systems/inventory';
import { createDummyFromSpawn } from './systems/enemy-spawn';
import { createBreakablesFromZone } from './systems/breakables';
import { createStarterSkills } from './systems/skills';
import { defaultUnlockedZones } from './systems/zone-travel';
import {
  WARRIOR_BASE,
  WARRIOR_STARTER,
  WARRIOR_STARTER_SPENT,
  xpToNextLevel,
} from './systems/stats';
import type { Player, World } from './types';
import { PLAYER, WORLD } from './config';

export function createPlayer(): Player {
  const player: Player = {
    x: WORLD.spawnX,
    y: WORLD.spawnY,
    prevX: WORLD.spawnX,
    prevY: WORLD.spawnY,
    vx: 0,
    vy: 0,
    w: PLAYER.width,
    h: PLAYER.height,
    facing: 1,
    onGround: false,
    coyote: 0,
    jumpBuffer: 0,
    state: 'idle',
    rollT: 0,
    rollCd: 0,
    attackT: 0,
    attackCd: 0,
    attackKind: 'basic',
    slamCd: 0,
    bashCd: 0,
    iFrame: 0,
    hitStop: 0,
    drinkT: 0,
    level: WARRIOR_STARTER.level,
    xp: 0,
    xpToNext: xpToNextLevel(WARRIOR_STARTER.level),
    baseStr: WARRIOR_BASE.str,
    baseAgi: WARRIOR_BASE.agi,
    baseInt: WARRIOR_BASE.int,
    baseVit: WARRIOR_BASE.vit,
    baseSpi: WARRIOR_BASE.spi,
    spentStr: WARRIOR_STARTER_SPENT.str,
    spentAgi: WARRIOR_STARTER_SPENT.agi,
    spentInt: WARRIOR_STARTER_SPENT.int,
    spentVit: WARRIOR_STARTER_SPENT.vit,
    spentSpi: WARRIOR_STARTER_SPENT.spi,
    unspentAttr: 0,
    unspentSkill: 1,
    str: 0,
    agi: 0,
    int: 0,
    vit: 0,
    spi: 0,
    weaponAtk: WARRIOR_STARTER.weaponAtk,
    armorDef: WARRIOR_STARTER.armorDef,
    atk: 0,
    def: 0,
    critChance: 0,
    critMult: 1.5,
    hp: 1,
    maxHp: 1,
    rage: PLAYER.bashCost,
    maxRage: PLAYER.maxRage,
    combatT: 0,
    rageWarnT: 0,
    hurtT: 0,
    deadT: 0,
    slowT: 0,
    petrifyT: 0,
    awaitRespawn: false,
    hasBanner: true,
    bannerX: 2.35,
    bannerY: 1,
    levelFxT: 0,
    weaponEnhance: 0,
    attrResetCount: 0,
    skillResetCount: 0,
    specResetCount: 0,
  };
  return player;
}

export function createWorld(zoneId = START_ZONE_ID): World {
  const zone = ZONES[zoneId] ?? ZONES[START_ZONE_ID];
  const starter = createStarterInventory();
  const dummies = zone.spawns.map((spawn, i) =>
    createDummyFromSpawn(i + 1, spawn.enemyId, spawn.x, spawn.y, spawn.patrolMin, spawn.patrolMax),
  );
  const world: World = {
    zoneId: zone.id,
    platforms: zonePlatforms(zone),
    rivers: zone.rivers.map((r) => ({ ...r })),
    banners: zone.banners.map((b) => ({ ...b })),
    player: createPlayer(),
    dummyId: dummies.length,
    hazards: [],
    hazardId: 0,
    projectiles: [],
    projectileId: 0,
    popups: [],
    popupId: 0,
    dusts: [],
    dustId: 0,
    lootFlies: [],
    lootFlyId: 0,
    loots: [],
    lootId: 0,
    gold: starter.gold,
    bag: starter.bag,
    itemUid: 2,
    mainhandUid: starter.bag[0]?.uid ?? null,
    invOpen: false,
    charOpen: false,
    skillOpen: false,
    catalogOpen: false,
    settingsOpen: false,
    campOpen: null,
    nearbyCamp: null,
    campMessage: '',
    nearbyHubPortal: false,
    unlockedZones: defaultUnlockedZones(),
    attrDraft: { str: 0, agi: 0, int: 0, vit: 0, spi: 0 },
    skills: createStarterSkills(),
    specId: null,
    specPickOpen: false,
    nearbyLootName: null,
    secretsClaimed: {},
    nearbySecretId: null,
    bossKills: {},
    ngPlusLevel: 0,
    challengeActive: false,
    challengeT: 0,
    discoveredLegendaries: [],
    tutorialStep: 'move',
    tutorialDone: false,
    tutorialAttrHint: false,
    tutorialSkillHint: false,
    breakables: createBreakablesFromZone(zone.id),
    kitTheme: zone.theme,
    shake: 0,
    levelToastT: 0,
    levelToastText: '',
    dummies,
  };
  applyGearStats(world.player, world);
  return world;
}
