import { START_ZONE_ID, ZONES, zonePlatforms } from './data/zones';
import { CLASS_DEFS, type PlayerClassId } from './data/classes';
import { createStarterInventory, applyGearStats } from './systems/inventory';
import { createDummyFromSpawn } from './systems/enemy-spawn';
import { createBreakablesFromZone } from './systems/breakables';
import { createStarterSkills, createStarterSkillBar } from './systems/skills';
import { defaultUnlockedZones } from './systems/zone-travel';
import { xpToNextLevel } from './systems/stats';
import type { Player, World } from './types';
import { PLAYER, WORLD } from './config';

export function createPlayer(classId: PlayerClassId = 'warrior'): Player {
  const cls = CLASS_DEFS[classId];
  const player: Player = {
    x: WORLD.spawnX,
    y: WORLD.spawnY,
    prevX: WORLD.spawnX,
    prevY: WORLD.spawnY,
    vx: 0,
    vy: 0,
    w: PLAYER.width,
    h: PLAYER.height,
    facing: 1,
    onGround: false,
    coyote: 0,
    jumpBuffer: 0,
    state: 'idle',
    rollT: 0,
    rollCd: 0,
    attackT: 0,
    attackCd: 0,
    attackKind: 'basic',
    slamCd: 0,
    bashCd: 0,
    skillCd2: 0,
    skillCd3: 0,
    missileBurstLeft: 0,
    missileBurstAcc: 0,
    iFrame: 0,
    hitStop: 0,
    drinkT: 0,
    potionCd: 0,
    classId,
    level: 1,
    xp: 0,
    xpToNext: xpToNextLevel(1),
    baseStr: cls.base.str,
    baseAgi: cls.base.agi,
    baseInt: cls.base.int,
    baseVit: cls.base.vit,
    baseSpi: cls.base.spi,
    spentStr: cls.starterSpent.str,
    spentAgi: cls.starterSpent.agi,
    spentInt: cls.starterSpent.int,
    spentVit: cls.starterSpent.vit,
    spentSpi: cls.starterSpent.spi,
    unspentAttr: 0,
    unspentSkill: 1,
    str: 0,
    agi: 0,
    int: 0,
    vit: 0,
    spi: 0,
    weaponAtk: cls.weaponAtk,
    armorDef: cls.armorDef,
    atk: 0,
    sp: 0,
    def: 0,
    critChance: 0,
    critMult: 1.5,
    hp: 1,
    maxHp: 1,
    rage: classId === 'mage' || classId === 'hunter' || classId === 'rogue' || classId === 'paladin' ? cls.maxResource : PLAYER.bashCost,
    maxRage: cls.maxResource,
    combatT: 0,
    rageWarnT: 0,
    hurtT: 0,
    deadT: 0,
    deathCause: 'none',
    fallWarnT: 0,
    slowT: 0,
    petrifyT: 0,
    awaitRespawn: false,
    hasBanner: true,
    bannerX: 2.35,
    bannerY: 1,
    levelFxT: 0,
    weaponEnhance: 0,
    attrResetCount: 0,
    skillResetCount: 0,
    specResetCount: 0,
    comboPoints: 0,
    sprintT: 0,
    vanishT: 0,
    openerBonusT: 0,
    rapidFireT: 0,
    rapidFireAcc: 0,
    skillShotArmed: false,
    manaShieldOn: false,
    manaShieldHp: 0,
    chargeDrT: 0,
    warShoutT: 0,
    sliceT: 0,
  };
  return player;
}

export function createWorld(zoneId = START_ZONE_ID, classId: PlayerClassId = 'warrior'): World {
  const zone = ZONES[zoneId] ?? ZONES[START_ZONE_ID];
  const starter = createStarterInventory(classId);
  const dummies = zone.spawns.map((spawn, i) =>
    createDummyFromSpawn(i + 1, spawn.enemyId, spawn.x, spawn.y, spawn.patrolMin, spawn.patrolMax),
  );
  const world: World = {
    zoneId: zone.id,
    platforms: zonePlatforms(zone),
    rivers: zone.rivers.map((r) => ({ ...r })),
    banners: zone.banners.map((b) => ({ ...b })),
    player: createPlayer(classId),
    dummyId: dummies.length,
    hazards: [],
    hazardId: 0,
    projectiles: [],
    projectileId: 0,
    traps: [],
    trapId: 0,
    blizzards: [],
    blizzardId: 0,
    popups: [],
    popupId: 0,
    dusts: [],
    dustId: 0,
    lootFlies: [],
    lootFlyId: 0,
    loots: [],
    lootId: 0,
    gold: starter.gold,
    bag: starter.bag,
    itemUid: starter.itemUid,
    mainhandUid: starter.bag[0]?.uid ?? null,
    invOpen: false,
    charOpen: false,
    skillOpen: false,
    catalogOpen: false,
    settingsOpen: false,
    levelUpOpen: false,
    levelUpGainAttr: 0,
    levelUpGainSkill: 0,
    campOpen: null,
    nearbyCamp: null,
    campMessage: '',
    nearbyHubPortal: false,
    unlockedZones: defaultUnlockedZones(),
    attrDraft: { str: 0, agi: 0, int: 0, vit: 0, spi: 0 },
    skills: createStarterSkills(classId),
    skillBar: createStarterSkillBar(classId),
    specId: null,
    specPickOpen: false,
    specNodes: {},
    specNodePickTier: null,
    nearbyLootName: null,
    nearbyLootCompare: null,
    nearbyLootTone: null,
    secretsClaimed: {},
    nearbySecretId: null,
    bossKills: {},
    ngPlusLevel: 0,
    challengeActive: false,
    challengeT: 0,
    challengeFloor: 0,
    challengeBestFloor: 0,
    challengeRunAffixes: [],
    discoveredLegendaries: [],
    tutorialStep: 'move',
    tutorialDone: false,
    tutorialAttrHint: false,
    tutorialSkillHint: false,
    breakables: createBreakablesFromZone(zone.id),
    kitTheme: zone.theme,
    shake: 0,
    levelToastT: 0,
    levelToastText: '',
    zoneAnnounceT: 0,
    zoneAnnounceName: '',
    zoneAnnounceSub: '',
    offerNgPlusHint: false,
    bossGateClosed: false,
    bossGateX: 0,
    slowMoT: 0,
    exploreTrail: [],
    dummies,
  };
  applyGearStats(world.player, world);
  return world;
}
