/** 与 `docs/ASSET_LIST.md` P0 路径一致。 */
export const ASSET = {
  skyDay: '/assets/zone/a01/a01-sky-day-nosun.png',
  moon: '/assets/zone/a01/moon-albedo.png',
  rock: '/assets/zone/a01/rock-albedo.png',
  leaf: '/assets/zone/a01/leaf-albedo.png',
  grass: '/assets/zone/a01/grass-albedo.png',
  farRidge: '/assets/zone/a01/a01-far-ridge.png',
  midTrees: '/assets/zone/a01/a01-mid-trees.png',
  fgTrunk: '/assets/zone/a01/a01-fg-trunk.png',
  ground: '/assets/zone/a01/a01-ground-albedo.png',
  platform: '/assets/zone/a01/a01-platform-albedo.png',
  bark: '/assets/zone/a01/a01-bark-albedo.png',
  moss: '/assets/zone/a01/a01-moss-trim.png',
  warrior: '/assets/char/warrior-side.png',
  rotwolf: '/assets/char/enemy/enemy-rotwolf-side.png',
  treant: '/assets/char/enemy/enemy-treant-side.png',
  wood: '/assets/prop/camp/camp-wood-albedo.png',
  firepit: '/assets/prop/camp/camp-firepit.png',
  forge: '/assets/prop/camp/camp-forge.png',
  stall: '/assets/prop/camp/camp-stall.png',
  teleport: '/assets/prop/camp/camp-teleport.png',
  palisade: '/assets/prop/camp/camp-palisade.png',
  torch: '/assets/zone/kit/kit-torch.png',
  banner: '/assets/zone/kit/kit-banner-flag.png',
  slash: '/assets/vfx/slash-arc.png',
  ember: '/assets/vfx/ember-particle.png',
  hitSpark: '/assets/vfx/hit-spark.png',
} as const;
